name: Duck
icon: "🦆"
maxWeight: 1
maxAmount: 200
maxSpeed: 4
maxFood: 0.15
reproduceChance: 0.15

diet:
  Wolf: 0
  Boa: 0
  Fox: 0
  Bear: 0
  Eagle: 0
  Horse: 0
  Deer: 5
  Rabbit: 0
  Mouse: 0
  Goat: 0
  Sheep: 0
  Boar: 0
  Buffalo: 0
  Duck: 0
  Caterpillar: 90
  Plant: 100