name: Boa
icon: "🐍"
maxWeight: 50
maxAmount: 30
maxSpeed: 1
maxFood: 3
reproduceChance: 0.2

diet:
  Wolf: 0
  Boa: 0
  Fox: 15
  Bear: 0
  Eagle: 0
  Horse: 0
  Deer: 0
  Rabbit: 20
  Mouse: 40
  Goat: 0
  Sheep: 0
  Boar: 0
  Buffalo: 0
  Duck: 10
  Caterpillar: 0
  Plant: 0